# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4a61d649286f570dae4abd6cb7085657a6a7ebb5c644914876ab2e6bd3ed5aff0636cef6b848b6a4f2d510c5d2646b5f6bf42a09d8653f2ec1b35b7ad82c54e4

test:
  secret_key_base: d254ae19691df673d747ffbb0f3f95178f8254c38c301f4760166c76bd69382c9c5f8fc18871357c79875ae847fc8b98d4116de2db99d19890b51187634ee5ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
